#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

main() {
  info "applying current config"

  if os_specific_apply_command; then
    success "applied config"
  else
    fail "failed to apply config"
  fi
}

os_specific_apply_command() {
  if "$DOTFILES/infra/scripts/is_macos.sh"; then
    # TODO: figure out passing in home-manager input from flake
    darwin-rebuild switch --flake ~/.files --impure --show-trace
  else # TODO: account for NixOS when supported in the future
    home-manager switch
  fi
}

main
