#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

main() {
  local config
  config="${1:-default}"

  info "applying '$config' config"

  if os_specific_apply_command "$@"; then
    success "applied '$config' config"
    return 0
  else
    fail "failed to apply '$config' config"
    return 1
  fi
}

os_specific_apply_command() {
  local config
  config="$1"

  if "$DOTFILES/infra/scripts/is_macos.sh"; then
    local maybe_verbose
    if [ -z "$VERBOSE" ]; then
      maybe_verbose=
    else
      maybe_verbose="--show-trace"
    fi

    # `--impure` allows access to environment variables
    # trade-off between purely reproducible config and one that can adjust
    # based off environment
    # TODO: figure out passing in home-manager input from flake
    # TODO: make machine specific configurations?
    info "applying \`${config:-default}\`"
    darwin-rebuild switch --flake "$DOTFILES#${config:-default}" --impure $maybe_verbose
  else # TODO: account for NixOS when supported in the future
    home-manager switch
  fi
}

main "$@"
