#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

main() {
  info "applying current config"

  if os_specific_apply_command "$@"; then
    success "applied config"
    return 0
  else
    fail "failed to apply config"
    return 1
  fi
}

os_specific_apply_command() {
  config="$1"

  if "$DOTFILES/infra/scripts/is_macos.sh"; then
    # `--impure` allows access to environment variables
    # trade-off between purely reproducible config and one that can adjust
    # based off environment
    # TODO: figure out passing in home-manager input from flake
    # TODO: make machine specific configurations?
    darwin-rebuild switch --flake "$DOTFILES#${config:-default}" --impure --show-trace
  else # TODO: account for NixOS when supported in the future
    home-manager switch
  fi
}

main "$@"
