# corresponding functions defined in '$DOTFILES/functions/_fzf_functions'
alias rgz='fzf_rg_edit'
alias killp='fzf_kill_by_port'
alias findpath='fzf_find_path'
alias bif='fzf_brew_install'
alias bunf='fzf_brew_uninstall'
alias buf='fzf_brew_upgrade'
