#! /usr/bin/env sh

# increase/decrease alacritty font size

# mnemonic - `alacritty font up`
# for 2k monitor
alfup() {
  sed -i '' 's/size: .*/size: 16.0/g' "$DOTFILES/config.symlink/alacritty/alacritty.yml"
}

# mnemonic - `alacritty font up up`
# for 4k monitor
alfupup() {
  sed -i '' 's/size: .*/size: 19.0/g' "$DOTFILES/config.symlink/alacritty/alacritty.yml"
}

# mnemonic - `alacritty font down`
# for 2k 15 inch laptop
alfdo() {
  sed -i '' 's/size: .*/size: 13.0/g' "$DOTFILES/config.symlink/alacritty/alacritty.yml"
}
