#! /usr/bin/env sh

# increase/decrease alacritty font size

# mnemonic - `alacritty font up`
alfup() {
  sed -i '' 's/size: .*/size: 16.0/g' "$DOTFILES/config.symlink/alacritty/alacritty.yml"
}

# mnemonic - `alacritty font down`
alfdo() {
  sed -i '' 's/size: .*/size: 13.0/g' "$DOTFILES/config.symlink/alacritty/alacritty.yml"
}
