#! /bin/zsh
# Assorted git functions

# move forward linearly a given number of commits
function gforw() {
	git checkout $(git rev-list --topo-order HEAD..master | tail -$1 | head -1)
}

# move back linearly a given number of commits
function gback() {
	git checkout HEAD~$1
}

# make a quick fix at a previous commit
function gfix() {
	gback "$1"

	# attempts to delete fix if already merged
	if [ -n "$(git show-ref refs/heads/fix)" ]; then
		git branch -d fix
	fi

	git checkout -b fix
}

# rebase given branch (or master)
# on just made fix
function gffix() {
	git checkout "${1:-"master"}"
	git rebase -i fix
	git branch -d fix
}
