#! /usr/bin/env bash

# TODO: handle packages whose binary is different from the package name
# e.g. `, ripgrep` fails since the binary is actually `rg`. I think the best
# experience here would be to let the user select from a list of the binaries in
# the corresponding `/bin` directory (or just select it if there's only one)

command="$1"

[[ -z $command ]] && {
  cat << EOF
error: the following arguments were not provided

  <PACKAGE>

See all valid packages @ https://search.nixos.org/packages

USAGE:

  comma <PACKAGE>
EOF
  return 1
}

args=("${@:2}")

# use stable package set to take advantage of caching
# list of channels (corresponds to flakes) - https://status.nixos.org/
flake=github:nixos/nixpkgs/nixpkgs-20.09

# use darwin packages on macOS
"$DOTFILES/infra/scripts/is_macos.sh" && flake="$flake-darwin"

nix run "$flake#$command" -- "${args[@]}"
