#! /usr/bin/env sh

# usage: extract <file>
# description: extracts archived files / mounts disk images

# note: .dmg/hdiutil is Mac OS X-specific.

# ref - http://nparikh.org/notes/zshrc.txt
file="$1"

[ -f "$file" ] || {
  echo "'$file' is not a valid file"
  exit 1
}

case "$file" in
  *.tar.bz2) tar -jxvf "$file" ;;
  *.tar.gz) tar -zxvf "$file" ;;
  *.bz2) bunzip2 "$file" ;;
  *.dmg) hdiutil mount "$file" ;;
  *.gz) gunzip "$file" ;;
  *.tar) tar -xvf "$file" ;;
  *.tbz2) tar -jxvf "$file" ;;
  *.tgz) tar -zxvf "$file" ;;
  *.zip) unzip "$file" ;;
  *.ZIP) unzip "$file" ;;
  *.pax) pax -r < "$file" ;;
  *.pax.Z) uncompress "$file" --stdout | pax -r ;;
  *.rar) unrar x "$file" ;;
  *.Z) uncompress "$file" ;;
  *) echo "'$file' cannot be extracted/mounted via extract()" ;;
esac
