#! /usr/bin/env bash

# determine size of a file or total size of a directory
if du -b /dev/null > /dev/null 2>&1; then
  _fs_arg=-sbh
else
  _fs_arg=-sh
fi

# shellcheck disable=SC2048
if [[ -n $* ]]; then
  du "$_fs_arg" -- "$@"
else
  du "$_fs_arg" .[^.]* ./*
fi
