#! /bin/zsh

# list directories with fzf
# jump to
function jj() {
    local dir
    dir=$(fasd -Rdl |\
        sed "s:$HOME:~:" |\
        fzf --no-sort +m -q "$*" |\
        sed "s:~:$HOME:")\
    && cd "$dir"
}
