#! /usr/bin/env bash

# display markdown file using `mdcat` w/ a pager
# ref - https://github.com/lunaryorn/mdcat/issues/50

[[ -z $1 ]] && {
  echo 'No target given, aborting'
  return 1
}

mdcat $1 | less -R
