#! /usr/bin/env sh

if command -v brew > /dev/null; then
  echo 'brew'
elif command -v apt > /dev/null; then
  # not necessarily the best idea but yolo
  echo 'sudo apt'
else
  echo 'No expected package manager found'
  return
fi
