#! /usr/bin/env bash

# display markdown file using `mdcat` w/ a pager
# ref - https://github.com/lunaryorn/mdcat/issues/50

[[ -z $1 ]] && {
  echo 'No target given, aborting'
  return 1
}

# if multiple targets given, use `bat` on all
[[ -n $2 ]] && {
  bat "$@"
  return
}

if [[ $1 =~ \.md$ ]]; then
  mdcat "$1" | less --no-init --quit-if-one-screen --RAW-CONTROL-CHARS
else
  bat "$1"
fi
