#! /usr/bin/env bash

# render given args with best available command

[[ -z $1 ]] && {
  echo 'No target given, aborting'
  return 1
}

render_args() {
  # use `mdcat` when passed a single markdown file
  [[ -z $2 ]] && [[ $1 =~ \.md$ ]] && command -v mdcat > /dev/null && {
    # display markdown file using `mdcat` w/ a pager
    # ref - https://github.com/lunaryorn/mdcat/issues/50
    mdcat "$1" | less --no-init --quit-if-one-screen --RAW-CONTROL-CHARS
    return
  }

  command -v bat > /dev/null && bat_or_cat="bat" || bat_or_cat="cat"
  "$bat_or_cat" "$@"
}

render_args "$@"
