#! /usr/bin/env bash

# render given args with best available command
render_args() {
  # use `mdcat` when passed a single markdown file
  # TODO: use `mdcat` w/ multiple files all are `*.md`
  [[ -z $2 ]] && [[ $1 =~ \.md$ ]] && command -v mdcat > /dev/null && {
    # `--paginate` applies the pager defined in $PAGER (or $MDCAT_PAGER w/ a
    # default of `less --raw-control-characters`)
    mdcat --paginate "$1"
    return
  }

  local bat_or_cat
  command -v bat > /dev/null && bat_or_cat="bat" || bat_or_cat="cat"
  "$bat_or_cat" "$@"
}

render_args "$@"
