#! /usr/bin/env bash

# convert given video to gif
# ref - https://superuser.com/a/556031
to_gif() {
  local video_in_path gif_out_path
  video_in_path="$1"
  gif_out_path="${2:-${video_in_path%.*}.gif}"

  command -v ffmpeg > /dev/null || {
    cat << EOF
error: \`ffmpeg\` must be installed to create gifs
please install \`ffmpeg\` then try again

quick fixes:

w/ \`nix\`: \`nix-env -i ffmpeg-full\`
w/ \`brew\`: \`brew install ffmpeg\`
EOF
    return 1
  }

  if [[ -z $video_in_path ]]; then
    local video_in_formatted
    [[ -z $video_in_path ]] && video_in_formatted="<video_in_path>"

    cat << EOF
error: the following argument was not provided

  $video_in_formatted

USAGE:

  to_gif <VIDEO-IN-PATH> [GIF-OUT-PATH]
EOF
    return 1
  fi

  SCALE='-1:-1'
  [ "$(uname -s)" = Darwin ] && SCALE='iw*0.5:-1' # undo 2x pixels
  ffmpeg \
    -i "$video_in_path" \
    -map_metadata -1 \
    -vf "fps=15,scale=${SCALE}:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
    -loop 0 \
    "$gif_out_path"
}

to_gif "$@"
