#! /usr/bin/env bash

# delete given branch locally & remotely

[[ -z $1 ]] && {
  cat << EOF
error: the following arguments were not provided

  <BRANCH-NAME(S)>

USAGE:

  gdel <BRANCH-NAME(S)>...
EOF
  return 1
}

# `$@` holds all arguments
git branch --delete --force "$@"
git push origin --delete "$@"
