#! /usr/bin/env zsh

# rebase given branch on fix branch
# abort if no branch given
git rev-parse --quiet --verify "$1" > /dev/null 2>&1 || {
  maybe_err=$?
  echo "Sorry, that branch doesn't seem to exist"
  return $maybe_err
}

# abort if there are unstaged changes as this will cause rebase to fail
git diff-index --quiet HEAD -- || {
  maybe_err=$?
  echo 'You have unstaged changes, stash or commit them, then run again'
  return $maybe_err
}

# checkout branch to rebase on fix
git checkout "$1" || {
  maybe_err=$?
  echo 'Checkout failed, please fix the error then try again'
  return $maybe_err
}

# should not fail due to untracked changes as we checked previously
# delete branch only if merging succeeds
git rebase --interactive fix && git branch --delete fix
