#! /usr/bin/env zsh

# force pull tracking branch & reset to `origin/$1`
# passing a branch that is not a tracking branch of the checked out local branch will
# work though may be unintuitive
[[ -z $1 ]] && echo 'No branch given, aborting' && return 1

# only reset if we can't fast-forward
git pull --all || git reset --hard "origin/$1"
