#! /usr/bin/env bash

# Pull all remotes & hard reset to `origin/$1`
#
# For example, `gplf master` will pull all remotes and reset current branch to
# `origin/master`.
#
# Passing a branch that is not a tracking branch of the checked out local branch
# will still hard reset the current branch to the given branch.

[[ -z $1 ]] && {
  echo 'No branch given, aborting'
  return 1
}

# only reset if we can't fast-forward
git pull --all || git reset --hard "origin/$1"
