#! /usr/bin/env bash

# Pull all remotes & rebase current branch on `origin/$1`
#
# For example, `gplr master` rebases the current branch on `origin/master`
#
# Passing a branch that is not a tracking branch of the checked out local branch
# will still rebase the current branch on the given branch.

[[ -z $1 ]] && {
  echo 'No branch given, aborting'
  return 1
}

# only reset if we can't fast-forward
git fetch --all || git rebase --interactive "origin/$1"
