#! /usr/bin/env bash

# set alacritty to font size for 27 inch, 2k resolution monitor
# mnemonic - `alacritty font up`
sed -i '' 's/size: .*/size: 16.0/g' "$DOTFILES/config.symlink/alacritty/alacritty.yml"
