#! /usr/bin/env bash

# Rebase given branch on branch `fix`, abort if no branch given. Attempt to
# delete branch `fix` afterwards if rebase successful.
#
# Second part of 2 part workflow (w/ `gfix`) to quickly fix up a previous commit

branch="$1"

[[ -z $branch ]] && {
  echo 'No branch given, aborting'
  return 1
}

git rev-parse --quiet --verify "$branch" > /dev/null || {
  printf "Sorry, the branch '%s' doesn't seem to exist" "$branch"
  return 1
}

# abort if there are unstaged changes as this will cause rebase to fail
git diff-index --quiet HEAD -- || {
  echo 'You have unstaged changes, stash or commit them, then run again'
  return 1
}

# checkout branch to rebase on fix
git checkout "$branch" || {
  echo 'Checkout failed, please fix the error then try again'
  return 1
}

# should not fail due to untracked changes as we checked previously
# delete branch only if merging succeeds
git rebase --interactive fix && git branch --delete fix
