#! /usr/bin/env zsh

# Create a `fix` branch at the given hash or the given number of commits back
# based on argument. If argument is a # < 50 it's treated as a number of commits
# back, otherwise treated as a hash.
#
# First part of 2 part workflow (w/ `gffix`) to quickly fix up a previous commit

# attempt to delete `fix` branch if it exists
git rev-parse --quiet --verify fix > /dev/null && {
  git branch --delete fix || {
    # if deletion fails, echo reason then return with exit code
    echo "Deletion of 'fix' branch failed, delete it manually then try again"
    return 1
  }
}

# checkout out # commits back or specific hash depending on user input
# <-> matches any number of digits (`zsh` specific)
{ { [[ $1 = <-> ]] && (( $1 < 50 )) } && gback "$1" || git checkout "$1" } || {
  echo 'Checkout failed, please fix the error then try again'
  return 1
}

git checkout -b fix # `-b <branch>`
