#! /usr/bin/env bash

# move forward linearly a given number of commits
function gforw() {
  [[ -z $1 ]] && {
    cat << EOF
error: the following arguments were not provided

  <NUMBER-OF-COMMITS>

USAGE:

  gforw NUMBER-OF-COMMITS [BRANCH-NAME]

where BRANCH-NAME is the branch towards which to move (if none given assumes
\`main\` [falls back to \`master\`])
EOF
    return 1
  }

  local default

  # shellcheck disable=SC1090
  default="$(. "$DOTFILES"/utilities/git/functions/prefer_main.sh)"

  git checkout \
    "$(git rev-list --topo-order HEAD.."${2:-"$default"}" | tail -"$1" | head -1)"
}

gforw "$@"
