#! /usr/bin/env bash

# attach to given session if it exists, otherwise create it

session=$1

[[ -z $session ]] && {
  cat << EOF
error: the following arguments were not provided

  <SESSION-NAME>

USAGE:

  tan <SESSION-NAME>
EOF
  return 1
}

# `-t <target-[client|session|window|pane]>`
# `-s <session-name>`
tmux attach -t "$session" &> /dev/null || tmux new -s "$session"
unset session
