#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

main() {
  parse_input "$@"

  [[ $SHOULD_SETUP_DESKTOP_APPS == false ]] && exit 0

  command -v brew > /dev/null || {
    # shellcheck disable=SC2016
    fail 'Setting up desktop apps requires `brew` to be installed'
    exit 1
  }

  "$DOTFILES/infra/scripts/is_macos.sh" || {
    info 'Desktop app setup only supported for macOS currently'
    exit 1
  }

  # << casks setup >>
  [[ $SHOULD_SETUP_DESKTOP_APPS == true ]] || {
    user "set up desktop apps? (casks listed in $DOTFILES/gui/apps/Brewfile)?\
     (y/any other key)"

    read -r -s -n 1 maybe_continue < /dev/tty

    [[ $maybe_continue != 'y' ]] && {
      info "skipping cask setup"
      exit 0
    }
  }

  info 'setting up desktop apps (casks)'
  make apply-gui
  success "set up casks"
  # << end casks setup >>
}

# handle any arguments/flags
parse_input() {
  for opt in "$@"; do
    case $opt in
      --skip-desktop-apps)
        SHOULD_SETUP_DESKTOP_APPS=false
        ;;
      --setup-desktop-apps)
        SHOULD_SETUP_DESKTOP_APPS=true
        ;;
      --*)
        # shellcheck disable=SC2016
        printf 'invalid flag passed to `%s`\n' 'setup_desktop_apps'
        exit 1
        ;;
    esac
  done
}

main "$@"
