#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

"$DOTFILES/infra/scripts/is_macos.sh" || {
  info "these dotfiles don't use \`brew\` in Linux environments - skipping"
  return
}

command -v brew > /dev/null && {
  # shellcheck disable=SC2016
  info '`brew` installed, skipping installation'
  return
}

# shellcheck disable=SC2016
info '`brew` not installed, installing now...'

# installation - https://brew.sh/
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# fix permissions issues for `compinit` caused by Homebrew messing with things
function fix_permissions_issue() {
  local fix_permissions_commands

  # fix permissions on `/user/local/share/*` folder that Homebrew's installer
  # messes with
  # ref - https://stackoverflow.com/a/43544733
  # maybe do something from here? https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
  # TODO: confirm that chmod command fixes things as expected
  fix_permissions_commands="chmod -R go-w \"$(brew --prefix)/share\";"
  # autoload -U compaudit;\
  # compaudit | xargs chown -R \"$(whoami)\" > /dev/null;\
  # compaudit | xargs chmod go-w > /dev/null;"

  # TODO: run conditionally
  info "Fixing completions permission issue"
  # `--no-rcs` to avoid running `compinit` and triggering warnings that we're
  # about to fix
  zsh --no-rcs -c "$fix_permissions_commands" > /dev/null
}
fix_permissions_issue

brew analytics off # disable analytics
