#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

main() {
  parse_input "$@"

  [[ $SHOULD_SETUP_DESKTOP_APPS == false ]] && exit 0

  command -v brew > /dev/null || {
    # shellcheck disable=SC2016
    fail 'Setting up desktop apps requires `brew` to be installed'
    exit 1
  }

  "$DOTFILES/infra/scripts/is_macos.sh" || {
    info 'Desktop app setup only supported for macOS currently'
    exit 1
  }

  # << casks setup >>
  [[ $SHOULD_SETUP_DESKTOP_APPS == true ]] || {
    user "set up desktop apps? (casks listed in $DOTFILES/gui/apps/Brewfile)?\
     (y/any other key)"

    read -r -s -n 1 maybe_continue < /dev/tty

    [[ $maybe_continue != 'y' ]] && {
      info "skipping cask setup"
      exit 0
    }
  }

  info 'setting up desktop apps (casks)'
  brew bundle --file "$DOTFILES/gui/apps/Brewfile" --verbose
  success "set up casks"
  # << end casks setup >>

  setup_mas_apps
}

# TODO: separate out more cleanly, fix up rough spots (xcode auth)
setup_mas_apps() {
  user "set up Mac App Store apps (Xcode, Super Easy Timer, and Time Out)? \
This requires being signed in to the app store and will only install apps if \
you have previously installed them. (y/any other key)"

  read -r -s -n 1 maybe_continue < /dev/tty
  [[ $maybe_continue != 'y' ]] && {
    info "skipping Mac App Store apps"
    exit 0
  }

  command -v mas > /dev/null || brew install "mas"

  # Xcode - https://apps.apple.com/us/app/xcode/id497799835
  mas install 497799835
  # accept license so that installed components are usable
  sudo xcodebuild -license accept

  # Super Easy Timer (paid, $5) - https://apps.apple.com/us/app/super-easy-timer/id1353137878
  mas install 1353137878
  # Time Out (in-app purchases) - https://apps.apple.com/us/app/time-out-break-reminders/id402592703
  mas install 402592703
}

# handle any arguments/flags
parse_input() {
  for opt in "$@"; do
    case $opt in
      --skip-desktop-apps)
        SHOULD_SETUP_DESKTOP_APPS=false
        ;;
      --setup-desktop-apps)
        SHOULD_SETUP_DESKTOP_APPS=true
        ;;
      --*)
        # shellcheck disable=SC2016
        printf 'invalid flag passed to `%s`\n' 'setup_desktop_apps'
        exit 1
        ;;
    esac
  done
}

main "$@"
