#! /usr/bin/env bash

# shellcheck disable=SC1090,1091

# check that DOTFILES variable is defined
# relative path handling is tricky and never foolproof
# refs
#   - http://mywiki.wooledge.org/BashFAQ/028
#   - https://stackoverflow.com/questions/6659689/referring-to-a-file-relative-to-executing-script
source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"

# source so that `brew` is usable in the current shell for the next steps
source "$DOTFILES/gui/setup/setup_brew" || {
  echo 'Homebrew installation failed. Please fix any errors and try again.'
  exit 1
}

# run in separate subshells

# install casks in `$DOTFILES/gui/apps/Brewfile`
"$DOTFILES/gui/setup/setup_desktop_apps" "$@"

# symlink config files to their correct locations
"$DOTFILES/infra/setup/bin/symlink" "$@" --gui
