#! /usr/bin/env bash

# check that DOTFILES variable is defined
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"

source "$DOTFILES/infra/scripts/prompts.sh"

main() {
  parse_input "$@"

  [[ $SHOULD_SETUP_DESKTOP_APPS == false ]] && exit 0

  command -v brew > /dev/null || {
    # shellcheck disable=SC2016
    echo 'Setting up desktop apps requires `brew` to be installed'
    exit 1
  }

  "$DOTFILES/infra/scripts/is_macos.sh" || {
    echo 'Desktop app setup only supported for macOS currently'
    exit 1
  }

  # << casks setup >>
  [[ $SHOULD_SETUP_DESKTOP_APPS == true ]] || {
    user "set up desktop apps? (casks listed in $DOTFILES/gui/apps/Brewfile)?\
     (y/any other key)"

    read -r -s -n 1 maybe_continue < /dev/tty

    [[ "$maybe_continue" != 'y' ]] && {
      info "skipping cask setup"
      exit 0
    }
  }

  echo 'setting up desktop apps (casks)'
  brew bundle --file "$DOTFILES/gui/apps/Brewfile"
  success "set up casks"
  # << end casks setup >>

  command -v mas > /dev/null || brew install "mas"

  # this line will error unless you have purchased Super Easy Timer. Delete or
  # comment this line out to avoid errors.
  # TODO: check for apple account first?
  # ref - https://github.com/mas-cli/mas
  mas install 1353137878 # Super Easy Timer
}

# handle any arguments/flags
parse_input() {
  for opt in "$@"; do
    case $opt in
      --skip-desktop-apps)
        SHOULD_SETUP_DESKTOP_APPS=false
        ;;
      --setup-desktop-apps)
        SHOULD_SETUP_DESKTOP_APPS=true
        ;;
      --*)
        # shellcheck disable=SC2016
        printf 'invalid flag passed to `%s`\n' 'setup_desktop_apps'
        exit 1
        ;;
    esac
  done
}

main "$@"
