#! /usr/bin/env bash

# check that DOTFILES variable is defined
# relative path handling is tricky and never foolproof
# refs
#   - http://mywiki.wooledge.org/BashFAQ/028
#   - https://stackoverflow.com/questions/6659689/referring-to-a-file-relative-to-executing-script
# shellcheck disable=SC1090
source "${BASH_SOURCE%/*}/../../infra/setup/check_dotfiles_variable.sh"

# run in separate subshells

# set up casks in `$DOTFILES/gui/Brewfile`
"$DOTFILES/gui/setup/setup_desktop_apps" "$@"

# symlink config files to their correct locations
"$DOTFILES/infra/setup/bin/symlink" "$@" --gui
