# <<<<<<<< casks (only valid on macOS) >>>>>>>>
# see additional context on Brewfiles in $DOTFILES/Brewfile

cask_args appdir: '/Applications'

# <<<< apps >>>>

cask "1password"
cask "alfred"
cask "alt-tab"
cask "bartender"
cask "contexts"
cask "daisydisk"
cask "fantastical"
cask "firefox"
cask "flux"
cask "google-chrome"
cask "istat-menus"
cask "karabiner-elements"
cask "keycastr"
cask "marshallofsound-google-play-music-player"
cask "monitorcontrol"
cask "mpv"
cask "notion"
cask "private-internet-access"
cask "rectangle"
cask "slack"
cask "spotify"
cask "sound-control"
cask "steermouse"
cask "subler"
cask "ueli"
cask "visual-studio-code"
