#! /usr/bin/env bash

# filter and edit (w/ `$EDITOR`) lines containing given query
# TODO: see if search term can be changed interactively
#
# ref - https://bluz71.github.io/2018/11/26/fuzzy-finding-in-bash-with-fzf.html#find-file-and-edit
[[ $# == 0 ]] && {
  echo 'Error: search term was not provided.'
  return
}

# TODO: allow multi select here
match=$(
  "$NIX_PROFILE/bin/rg" --color=never --line-number "$1" \
    | fzf --no-multi --delimiter : \
      --preview "bat --color=always --line-range {2}: {1}"
)
# TODO: use `printf` not `echo`
file=$(echo "$match" | cut -d':' -f1)
[[ -n $file ]] && "$EDITOR" "$file" +"$(echo "$match" | cut -d':' -f2)"
unset match file
