#! /usr/bin/env zsh

# edit selected file w/ `$EDITOR` (falling back to `nvim` if not set)
# lightly adapted from `fzf-cd-widget`
setopt localoptions pipefail 2> /dev/null
file="$(
  eval "$FZF_DEFAULT_COMMAND --type file" \
    | FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $FZF_EDIT_OPTS" $(__fzfcmd) +m
  )"

if [[ -z "$file" ]]; then
  zle redisplay
  return 0
fi

"${EDITOR:-nvim}" "$file"

unset file

_fzf_edit_widget_ret=$?
zle fzf-redraw-prompt
return "$_fzf_edit_widget_ret"
