#! /usr/bin/env bash

# filter and edit (w/ `$EDITOR`) lines containing given query
# TODO: see if search term can be changed interactively
#
# ref - https://bluz71.github.io/2018/11/26/fuzzy-finding-in-bash-with-fzf.html#find-file-and-edit
if [[ $# == 0 ]]; then
    echo 'Error: search term was not provided.'
    return
fi
# TODO: allow multi select here
match=$(
  rg --color=never --line-number "$1" |
    fzf --no-multi --delimiter : \
        --preview "bat --color=always --line-range {2}: {1}"
)
file=$(echo "$match" | cut -d':' -f1)
if [[ -n $file ]]; then
    "$EDITOR" "$file" +"$(echo "$match" | cut -d':' -f2)"
fi
unset match file
