#! /usr/bin/env bash

# filter and output files shown by `git status` (untracked, unstaged, staged) to
# shell

"$DOTFILES/infra/scripts/is_in_git_repo.sh" || return

preview='(git diff --color=always -- {-1} | sed 1,4d; cat {-1}) | bat'

git -c color.status=always status --short \
  | fzf -m --ansi --nth 2..,.. --preview "$preview" \
  | cut -c4- | sed 's/.* -> //'
unset preview
