#! /usr/bin/env bash

# edit selected file w/ `$EDITOR` (falling back to `nvim` if not set)
# lightly adapted from `fzf-cd-widget`
setopt localoptions pipefail 2> /dev/null
files=$(
  eval "$FZF_CTRL_T_COMMAND" \
    | FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $FZF_EDIT_OPTS" $(__fzfcmd) -m
)

[[ -z $files ]] && {
  zle redisplay
  return 0
}

# TODO: figure out why calling echo here changes things
# TODO: use `printf` not `echo`
# shellcheck disable=SC2046,SC2116,SC2086
"${EDITOR:-nvim}" $(echo $files)

unset files

_fzf_edit_widget_ret=$?
zle reset-prompt
return "$_fzf_edit_widget_ret"
