#! /usr/bin/env bash

# filter `git log` commits and output hash to shell

"$DOTFILES/infra/scripts/is_in_git_repo.sh" || return

format='%C(green)%C(bold)%cd %C(auto)%h%d %s (%an)'
bindings='ctrl-s:toggle-sort,ctrl-space:toggle-preview'
preview='grep -o "[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} [a-f0-9]\{7\}" <<< {} | cut -d " " -f 2 | xargs git show --color=always | bat'

git log --date=short --format="$format" --graph --color=always \
  | fzf --ansi --no-sort --reverse --multi --bind "$bindings" \
    --header 'Press CTRL-S to toggle sort' \
    --preview "$preview" \
  | grep -o "[a-f0-9]\{7,\}"

unset format bindings preview
