#! /usr/bin/env zsh

# fuzzy select files containing given term
# TODO: see if search term can be changed interactively
#
# ref - https://bluz71.github.io/2018/11/26/fuzzy-finding-in-bash-with-fzf.html#find-file-and-edit
if [[ $# == 0 ]]; then
    echo 'Error: search term was not provided.'
    return
fi
local match=$(
  rg --color=never --line-number "$1" |
    fzf --no-multi --delimiter : \
        --preview "bat --color=always --line-range {2}: {1}"
  )
local file=$(echo "$match" | cut -d':' -f1)
if [[ -n $file ]]; then
    $EDITOR $file +$(echo "$match" | cut -d':' -f2)
fi
