#! /usr/bin/env zsh

# list directories in $PATH, press `enter` on an entry to list contained
# executables.  press `escape` to go back to directory listing, `escape` again
# to exit completely
# ref - https://github.com/SidOfc/dotfiles/blob/d07fa3862ed065c2a5a7f1160ae98416bfe2e1ee/zsh/fp
local loc=$(echo $PATH | sed -e $'s/:/\\\n/g' | eval "fzf ${FZF_DEFAULT_OPTS} --header='[find:path]'")

if [[ -d $loc ]]; then
  echo "$(\
      rg --files $loc |\
      rev |\
      cut -d"/" -f1 |\
      rev\
    )" |\
    eval "fzf ${FZF_DEFAULT_OPTS} ='[find:exe] => ${loc}' >/dev/null"

  fzf_find_path
fi
