#! /usr/bin/env bash

main() {
  set -euo pipefail
  local filter root

  # blacklist third-party directories
  filter='gui/apps/alfred'
  root="$(git rev-parse --show-toplevel)"

  cd "$root"

  # pass through any function args to `shfmt`, used in ci to pass `-d` to error
  # on diff, also enables easy auto-fixing w/ `infra/action/shfmt -w -s` (`-w`
  # write to file, `-s` simplify)
  # `shfmt` args should be kept in sync with alias in `$DOTFILES/zsh/alias.zsh`
  # shellcheck disable=SC2086
  shfmt -f . | grep -v "$filter" | xargs shfmt -i 2 -bn -ci -sr "$@"
}

main "$@"
