#! /usr/bin/env bash

set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"

# blacklist third-party directories
filter=(
  ':!:apps/alfred'
)

{
  # `.sh` extension
  git ls-files '*.sh' -- "${filter[@]}"
  # `#! usr/bin/env bash` shebang
  git grep -l '^\(#! */usr/bin/env bash\|#! */bin/bash\)$' -- "${filter[@]}"
  # remove duplicates from .sh + shebang
  # `shfmt` args should match the alias in `$DOTFILES/zsh/alias.zsh`
} | sort | uniq | xargs shfmt -i 2 -bn -ci -sr -d || exit 1
