#! /usr/bin/env bash

# why set things up manually when other
# people have written nice scripts :)

set -e

# import prompts
# technically not necessary currently
source $DOTFILES/setup/lib/prompts.sh

echo ''
source $DOTFILES/setup/bin/symlink
source $DOTFILES/setup/bin/setup_git_config
