# << stable >>

edition = "2018"
max_width = 80
tab_spaces = 2
use_field_init_shorthand = true

# << unstable >>
# fn_single_line = true
# format_code_in_doc_comments = true
# imports_layout = "HorizontalVertical"
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# report_fixme = "Unnumbered"
# report_todo = "Unnumbered"
# trailing_semicolon = false
# where_single_line = true
# wrap_comments = true
