#! /usr/bin/env bash

main() {
  local teal_highlight clear_highlight
  teal_highlight='\x1b[38;5;006m'
  clear_highlight='\x1b[0m\n\n'

  parse_input "$@"

  # check that DOTFILES variable is defined
  # relative path handling is tricky and never foolproof
  # refs
  #   - http://mywiki.wooledge.org/BashFAQ/028
  #   - https://stackoverflow.com/questions/6659689/referring-to-a-file-relative-to-executing-script
  # shellcheck disable=SC1091
  source "${BASH_SOURCE%/*}/check_dotfiles_variable.sh"

  printf "%bstarting dotfiles setup%b" "$teal_highlight" "$clear_highlight"

  "$DOTFILES/infra/scripts/is_apple_silicon.sh" && {
    # TODO: conditionally install rosetta by checking existence of
    # `/usr/libexec/rosetta` here when able to test on new machine
    #
    # refs:
    # - https://apple.stackexchange.com/a/427996
    # - https://forums.macrumors.com/threads/is-there-a-way-to-uninstall-rosetta-from-m1.2300470/
    printf "on Apple Silicon Mac, installing Rosetta"
    softwareupdate --install-rosetta --agree-to-license
  }

  # TODO: test if available for future setup steps
  # shellcheck disable=SC1091
  source "$DOTFILES/infra/setup/bin/setup_nix" || {
    # shellcheck disable=SC2016
    echo '`nix` installation failed.'
    # shellcheck disable=SC2016
    echo 'Try opening a new shell and rerunning `$DOTFILES/infra/setup/bin/setup_nix`'
    exit 1
  }

  # TODO: try separating this into two different setup scripts?
  # one base setup
  # one final pieces?

  # # TODO: figure out less hacky solution for making nix available?
  # source $HOME/.config/.zshrc

  # generate user-specific gitconfig (name & email) @ `$HOME/.gitconfig.local`
  "$DOTFILES/infra/setup/bin/setup_git_config" "$HOME/.gitconfig.local" --skip-existing

  # set up our shell (`zsh`)
  # this adds `zsh` to our allowed shells and sets it as the default. Then it
  # loads `zsh` for the first time to install plugins & complete setup.
  "$DOTFILES/infra/setup/bin/setup_zsh"

  # load neovim for the first time to install plugins
  "$DOTFILES/infra/setup/bin/setup_neovim"

  # set up various pieces too small for their own files
  # see the file in question for each piece
  "$DOTFILES/infra/setup/bin/setup_bits_and_pieces"

  # optionally set up work-specific config (confirms via user prompt)
  "$DOTFILES/infra/setup/bin/setup_work"

  printf "%bstarting new shell, happy coding!%b" "$teal_highlight" "$clear_highlight"
  printf "%bsetup finished! 🎉%b" "$teal_highlight" "$clear_highlight"

  zsh --interactive
}

parse_input() {
  for opt in "$@"; do
    case $opt in
      --headless)
        export DOTFILES_SETUP_HEADLESS=true
        ;;
      --*)
        # shellcheck disable=SC2016
        printf 'invalid flag passed to `setup_dotfiles`'
        exit 1
        ;;
    esac
  done
}

main "$@"
